use_wandb: false

device: cuda

batch_size: 32

vision_view: front
# vision_view: side

vae_epochs: 50
vae_lr: 0.001
vae_latent_dim: 1024

vae_modality: concat
# vae_modality: vision
# vae_modality: tactile

reg_epochs: 50
reg_lr: 0.001
reg_hidden_dim: 2048

remove_tactile_bg: True

aif_decoder_epochs: 10
aif_decoder_lr: 0.001
